# Publish the package to NPM and version bump each time a new release is published on Github.

name: Publish Package to NPM

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Setup the build server.
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Configure the automation bot details.
      - run: git config --global user.name "Publish Bot"
      - run: git config --global user.email "noreply@objektlabs.io"

      # Install package dependencies.
      - run: npm ci

      # Build the package.
      #- run: npm run build

      # Ensure all tests pass.
      - run: npm run test

      # Generate documentation.
      - run: npm run docs

      # Update package version number to release tag name.
      - run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      # Publish package to NPM
      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Push documentation and version number changes back into repo.
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}